version: '3.7'

services:
  project-webapi:
    build:
      context: .
      dockerfile: StudyProject.Webapi/Dockerfile
    environment:
      - CONN=Host=host.docker.internal,Port=5432,Database=postgres,User Id=postgres,Password=postgres
    ports:
      - "5000:80"
    depends_on:
      - project-db
    networks:
      - project-net

  project-db:
    image: postgres:9.5
    restart: always
    environment:  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - project-net

  pgadmin4:
    image: dpage/pgadmin4
    volumes:
      - pgservers:/servers.json
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: teste
    depends_on:
      - project-db
    networks:
      - project-net

volumes:
  pgdata:
  pgservers:

networks:
  project-net: